###Lấy tin nhắn của 1 nhóm
GET http://localhost:3000/chat/b1577a39-1b41-11ef-ac79-088fc368?page=1
###Lấy tin nhắn cuối cùng của group đó
GET http://localhost:3000/chat/last/09d1ce97-089e-11ef-aa1b-088fc368

###
POST  http://localhost:3000/chat
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjNWYwZTEyLWY2NzMtMTFlZS05NTRlLTA4OGZjMzY4IiwiaWF0IjoxNzEyNjc5MzQ2LCJleHAiOjE3MTI3NjU3NDZ9.d_NHZhmny2PUPzaPYjv1kG_mFuyMIMPJvn3mj60-7zw
Content-Type: application/json

{
    "content": "hello",
    "image": "",
    "id_group": "",
    "id_user":""
}