#Lấy Group
GET http://localhost:3000/group/b5b3190c-5397-11ee-b610-089798d3

#Lấy Member trong group đó
GET http://localhost:3000/group/member/43815472-0636-11ef-9802-088fc368

# Lấy trạng thái của nhóm chát đó đã đọc tin nhắn hay chưa
GET http://localhost:3000/group/(id user)/(id group)

#Đánh dấu đọc tin nhắn
PUT http://localhost:3000/group
{
  "id_group": "",
  "id_user":""
}

#Thay đổi tên ảnh hoặc chủ nhóm
PUT http://localhost:3000/group/Change
{
  "id":"",
  "name":"",
  "image": "",
  "id_user":"",
  "type": ""
}

#Tạo group
POST http://localhost:3000/group
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjNWYwZTEyLWY2NzMtMTFlZS05NTRlLTA4OGZjMzY4IiwiaWF0IjoxNzEyNjc5MzQ2LCJleHAiOjE3MTI3NjU3NDZ9.d_NHZhmny2PUPzaPYjv1kG_mFuyMIMPJvn3mj60-7zw
Content-Type: application/json

 {
  "name": "Test",
  "image": "jjj",
  "id_user": "b5b3190c-5397-11ee-b610-089798d3",
 }

 POST http://localhost:3000/group/member
 Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjNWYwZTEyLWY2NzMtMTFlZS05NTRlLTA4OGZjMzY4IiwiaWF0IjoxNzEyNjc5MzQ2LCJleHAiOjE3MTI3NjU3NDZ9.d_NHZhmny2PUPzaPYjv1kG_mFuyMIMPJvn3mj60-7zw
Content-Type: application/json

 {
  "id_user": "3c5f0e12-f673-11ee-954e-088fc368",
  "id_group": "ae0b710f-f747-11ee-9291-088fc368"
 }

#Xóa nhóm
 DELETE http://localhost:3000/group/7099008b-04be-11ef-9d0d-088fc368
#Thoát nhóm (xóa member ra khỏi nhóm đó) truyền vào là id user
  DELETE http://localhost:3000/group/member/7099008b-04be-11ef-9d0d-088fc368
