### User: Detail
GET http://localhost:3000/user/b5b3190c-5397-11ee-b610-089798d3

### User: Register
POST http://localhost:3000/user/register
Content-Type: application/json

 {
  "name": "Test",
  "username": "test",
  "password": "1234",
  "email": "admin@gmail.com"
 }

 ### User: Register volunteers
POST http://localhost:3000/user/register/volunteers
Content-Type: application/json

 {
  "name": "Volunteers",
  "username": "admin",
  "password": "1234",
  "email": "admin@gmail.com"
 }

 ### User: Register admin
POST http://localhost:3000/user/register/admin
Content-Type: application/json

 {
  "name": "Admin",
  "username": "admin",
  "password": "1234",
  "email": "admin@gmail.com"
 }

### User: login
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}

### User: update
PUT http://localhost:3000/user/b5b3190c-5397-11ee-b610-089798d3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI1YjMxOTBjLTUzOTctMTFlZS1iNjEwLTA4OTc5OGQzIiwiaWF0IjoxNjk3Njg5NzQzLCJleHAiOjE2OTc3NzYxNDN9.8vMBwKihv_7BB57q-_RAdT6zLrkhofwZxdbNjkIuAWk

{
  "name": "Admin",
  "avatar": null,
  "gender": 1,
  "birth_day": "2023-09-15",
  "phone": "0123456789"
}

### User: changePassword
PUT http://localhost:3000/user/change_password/b5b3190c-5397-11ee-b610-089798d3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI1YjMxOTBjLTUzOTctMTFlZS1iNjEwLTA4OTc5OGQzIiwiaWF0IjoxNjk3Njg5NzQzLCJleHAiOjE2OTc3NzYxNDN9.8vMBwKihv_7BB57q-_RAdT6zLrkhofwZxdbNjkIuAWk

{
  "oldPassword": "1234",
  "password": "1234"
}

### User: delete user
DELETE http://localhost:3000/user/98755211-6e39-11ee-8326-089798d3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk4NzU1MjExLTZlMzktMTFlZS04MzI2LTA4OTc5OGQzIiwiaWF0IjoxNjk3NjkwNDU2LCJleHAiOjE2OTc3NzY4NTZ9.h37imhJaX7PzpaaaN9kOf1FEIDgSDnVl8LgwVx8jBvU