### User: Detail
# GET http://localhost:3000/user/b5b3190c-5397-11ee-b610-089798d3
## Lấy tất cả user
GET http://localhost:3000/user
## Lấy user ko có trong nhóm đó (truyền id_group vào)
GET http://localhost:3000/user/member/76d4ee57-088a-11ef-aa1b-088fc368


### User: Register
POST http://localhost:3000/user/register
Content-Type: application/json

 {
  "name": "Test",
  "username": "jjj",
  "password": "1234",
  "email": "admin@gmail.com"
 }

### User: login
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "username": "ngat",
  "password": "1234"
}

### User: update
PUT http://localhost:3000/user/b5b3190c-5397-11ee-b610-089798d3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI1YjMxOTBjLTUzOTctMTFlZS1iNjEwLTA4OTc5OGQzIiwiaWF0IjoxNjk3Njg5NzQzLCJleHAiOjE2OTc3NzYxNDN9.8vMBwKihv_7BB57q-_RAdT6zLrkhofwZxdbNjkIuAWk

{
  "name": "Admin",
  "avatar": null,
  "gender": 1,
  "birth_day": "2023-09-15",
  "phone": "0123456789"
}

### User: changePassword
PUT http://localhost:3000/user/change_password/b5b3190c-5397-11ee-b610-089798d3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI1YjMxOTBjLTUzOTctMTFlZS1iNjEwLTA4OTc5OGQzIiwiaWF0IjoxNzE2NzEwMzAwLCJleHAiOjE3MTY3OTY3MDB9.4Xx1WOx8MhCT_ODm_2u2_PCsIzx61lqboZIffybX4iI

{
  "oldPassword": "1234",
  "password": "1234"
}

